//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.28 at 06:15:03 PM CST 
//


package com.amadeus.xml.tcdres_09_1_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amadeus.xml.tcdres_09_1_1a package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amadeus.xml.tcdres_09_1_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply }
     * 
     */
    public TicketProcessEDocCCConcealedReply createTicketProcessEDocCCConcealedReply() {
        return new TicketProcessEDocCCConcealedReply();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup createTicketProcessEDocCCConcealedReplyDocGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup createTicketProcessEDocCCConcealedReplyDocGroupCarrierFeeGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup createTicketProcessEDocCCConcealedReplyDocGroupFareElementsGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup createTicketProcessEDocCCConcealedReplyDocGroupFareElementsGroupFareComponentsGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup createTicketProcessEDocCCConcealedReplyDocGroupFareElementsGroupFareComponentsGroupPricedFareComponentsGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup createTicketProcessEDocCCConcealedReplyDocGroupDocDetailsGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup();
    }

    /**
     * Create an instance of {@link MessageActionDetailsTypeI }
     * 
     */
    public MessageActionDetailsTypeI createMessageActionDetailsTypeI() {
        return new MessageActionDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketAgentInfoTypeI }
     * 
     */
    public TicketAgentInfoTypeI createTicketAgentInfoTypeI() {
        return new TicketAgentInfoTypeI();
    }

    /**
     * Create an instance of {@link ReservationControlInformationTypeI }
     * 
     */
    public ReservationControlInformationTypeI createReservationControlInformationTypeI() {
        return new ReservationControlInformationTypeI();
    }

    /**
     * Create an instance of {@link MonetaryInformationTypeI }
     * 
     */
    public MonetaryInformationTypeI createMonetaryInformationTypeI() {
        return new MonetaryInformationTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingDetailsTypeI }
     * 
     */
    public PricingTicketingDetailsTypeI createPricingTicketingDetailsTypeI() {
        return new PricingTicketingDetailsTypeI();
    }

    /**
     * Create an instance of {@link OriginAndDestinationDetailsTypeI }
     * 
     */
    public OriginAndDestinationDetailsTypeI createOriginAndDestinationDetailsTypeI() {
        return new OriginAndDestinationDetailsTypeI();
    }

    /**
     * Create an instance of {@link TourInformationTypeI }
     * 
     */
    public TourInformationTypeI createTourInformationTypeI() {
        return new TourInformationTypeI();
    }

    /**
     * Create an instance of {@link FormOfPaymentTypeI }
     * 
     */
    public FormOfPaymentTypeI createFormOfPaymentTypeI() {
        return new FormOfPaymentTypeI();
    }

    /**
     * Create an instance of {@link NumberOfUnitsTypeI }
     * 
     */
    public NumberOfUnitsTypeI createNumberOfUnitsTypeI() {
        return new NumberOfUnitsTypeI();
    }

    /**
     * Create an instance of {@link TaxTypeI }
     * 
     */
    public TaxTypeI createTaxTypeI() {
        return new TaxTypeI();
    }

    /**
     * Create an instance of {@link ApplicationErrorInformationTypeI }
     * 
     */
    public ApplicationErrorInformationTypeI createApplicationErrorInformationTypeI() {
        return new ApplicationErrorInformationTypeI();
    }

    /**
     * Create an instance of {@link CouponInformationTypeI }
     * 
     */
    public CouponInformationTypeI createCouponInformationTypeI() {
        return new CouponInformationTypeI();
    }

    /**
     * Create an instance of {@link DocumentInformationDetailsTypeI }
     * 
     */
    public DocumentInformationDetailsTypeI createDocumentInformationDetailsTypeI() {
        return new DocumentInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link InteractiveFreeTextTypeI }
     * 
     */
    public InteractiveFreeTextTypeI createInteractiveFreeTextTypeI() {
        return new InteractiveFreeTextTypeI();
    }

    /**
     * Create an instance of {@link FareInformationTypeI }
     * 
     */
    public FareInformationTypeI createFareInformationTypeI() {
        return new FareInformationTypeI();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.GeneralDocGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.GeneralDocGroup createTicketProcessEDocCCConcealedReplyGeneralDocGroup() {
        return new TicketProcessEDocCCConcealedReply.GeneralDocGroup();
    }

    /**
     * Create an instance of {@link TravellerPriorityDetailsTypeI }
     * 
     */
    public TravellerPriorityDetailsTypeI createTravellerPriorityDetailsTypeI() {
        return new TravellerPriorityDetailsTypeI();
    }

    /**
     * Create an instance of {@link BaggageDetailsTypeI }
     * 
     */
    public BaggageDetailsTypeI createBaggageDetailsTypeI() {
        return new BaggageDetailsTypeI();
    }

    /**
     * Create an instance of {@link FrequentTravellerIdentificationTypeI }
     * 
     */
    public FrequentTravellerIdentificationTypeI createFrequentTravellerIdentificationTypeI() {
        return new FrequentTravellerIdentificationTypeI();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI }
     * 
     */
    public MonetaryInformationDetailsTypeI createMonetaryInformationDetailsTypeI() {
        return new MonetaryInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link SystemDetailsTypeI }
     * 
     */
    public SystemDetailsTypeI createSystemDetailsTypeI() {
        return new SystemDetailsTypeI();
    }

    /**
     * Create an instance of {@link AdditionalProductDetailsTypeI }
     * 
     */
    public AdditionalProductDetailsTypeI createAdditionalProductDetailsTypeI() {
        return new AdditionalProductDetailsTypeI();
    }

    /**
     * Create an instance of {@link ProductTypeDetailsTypeI }
     * 
     */
    public ProductTypeDetailsTypeI createProductTypeDetailsTypeI() {
        return new ProductTypeDetailsTypeI();
    }

    /**
     * Create an instance of {@link ExcessBaggageDetailsTypeI }
     * 
     */
    public ExcessBaggageDetailsTypeI createExcessBaggageDetailsTypeI() {
        return new ExcessBaggageDetailsTypeI();
    }

    /**
     * Create an instance of {@link TourDetailsTypeI }
     * 
     */
    public TourDetailsTypeI createTourDetailsTypeI() {
        return new TourDetailsTypeI();
    }

    /**
     * Create an instance of {@link ConversionRateTypeI }
     * 
     */
    public ConversionRateTypeI createConversionRateTypeI() {
        return new ConversionRateTypeI();
    }

    /**
     * Create an instance of {@link TravelProductInformationTypeI }
     * 
     */
    public TravelProductInformationTypeI createTravelProductInformationTypeI() {
        return new TravelProductInformationTypeI();
    }

    /**
     * Create an instance of {@link CompanyIdentificationTypeI }
     * 
     */
    public CompanyIdentificationTypeI createCompanyIdentificationTypeI() {
        return new CompanyIdentificationTypeI();
    }

    /**
     * Create an instance of {@link ProductDateTimeTypeI }
     * 
     */
    public ProductDateTimeTypeI createProductDateTimeTypeI() {
        return new ProductDateTimeTypeI();
    }

    /**
     * Create an instance of {@link ExcessBaggageTypeI }
     * 
     */
    public ExcessBaggageTypeI createExcessBaggageTypeI() {
        return new ExcessBaggageTypeI();
    }

    /**
     * Create an instance of {@link StatusDetailsTypeI }
     * 
     */
    public StatusDetailsTypeI createStatusDetailsTypeI() {
        return new StatusDetailsTypeI();
    }

    /**
     * Create an instance of {@link CompanyIdentificationNumbersTypeI }
     * 
     */
    public CompanyIdentificationNumbersTypeI createCompanyIdentificationNumbersTypeI() {
        return new CompanyIdentificationNumbersTypeI();
    }

    /**
     * Create an instance of {@link ProductLocationDetailsTypeI }
     * 
     */
    public ProductLocationDetailsTypeI createProductLocationDetailsTypeI() {
        return new ProductLocationDetailsTypeI();
    }

    /**
     * Create an instance of {@link CouponInformationDetailsTypeI }
     * 
     */
    public CouponInformationDetailsTypeI createCouponInformationDetailsTypeI() {
        return new CouponInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingInformationTypeI }
     * 
     */
    public PricingTicketingInformationTypeI createPricingTicketingInformationTypeI() {
        return new PricingTicketingInformationTypeI();
    }

    /**
     * Create an instance of {@link DataInformationTypeI }
     * 
     */
    public DataInformationTypeI createDataInformationTypeI() {
        return new DataInformationTypeI();
    }

    /**
     * Create an instance of {@link OriginatorOfRequestDetailsTypeI }
     * 
     */
    public OriginatorOfRequestDetailsTypeI createOriginatorOfRequestDetailsTypeI() {
        return new OriginatorOfRequestDetailsTypeI();
    }

    /**
     * Create an instance of {@link SelectionDetailsInformationTypeI }
     * 
     */
    public SelectionDetailsInformationTypeI createSelectionDetailsInformationTypeI() {
        return new SelectionDetailsInformationTypeI();
    }

    /**
     * Create an instance of {@link FreeTextQualificationTypeI }
     * 
     */
    public FreeTextQualificationTypeI createFreeTextQualificationTypeI() {
        return new FreeTextQualificationTypeI();
    }

    /**
     * Create an instance of {@link DateAndTimeInformationTypeI }
     * 
     */
    public DateAndTimeInformationTypeI createDateAndTimeInformationTypeI() {
        return new DateAndTimeInformationTypeI();
    }

    /**
     * Create an instance of {@link TravellerDetailsTypeI }
     * 
     */
    public TravellerDetailsTypeI createTravellerDetailsTypeI() {
        return new TravellerDetailsTypeI();
    }

    /**
     * Create an instance of {@link FareComponentInformationTypeI }
     * 
     */
    public FareComponentInformationTypeI createFareComponentInformationTypeI() {
        return new FareComponentInformationTypeI();
    }

    /**
     * Create an instance of {@link NumberOfUnitDetailsTypeI }
     * 
     */
    public NumberOfUnitDetailsTypeI createNumberOfUnitDetailsTypeI() {
        return new NumberOfUnitDetailsTypeI();
    }

    /**
     * Create an instance of {@link TravellerSurnameInformationTypeI }
     * 
     */
    public TravellerSurnameInformationTypeI createTravellerSurnameInformationTypeI() {
        return new TravellerSurnameInformationTypeI();
    }

    /**
     * Create an instance of {@link OriginatorDetailsTypeI }
     * 
     */
    public OriginatorDetailsTypeI createOriginatorDetailsTypeI() {
        return new OriginatorDetailsTypeI();
    }

    /**
     * Create an instance of {@link ItemNumberTypeI }
     * 
     */
    public ItemNumberTypeI createItemNumberTypeI() {
        return new ItemNumberTypeI();
    }

    /**
     * Create an instance of {@link CompanyIdentificationTypeI83773C }
     * 
     */
    public CompanyIdentificationTypeI83773C createCompanyIdentificationTypeI83773C() {
        return new CompanyIdentificationTypeI83773C();
    }

    /**
     * Create an instance of {@link RoutingInformationTypeI }
     * 
     */
    public RoutingInformationTypeI createRoutingInformationTypeI() {
        return new RoutingInformationTypeI();
    }

    /**
     * Create an instance of {@link ConsumerReferenceIdentificationTypeI }
     * 
     */
    public ConsumerReferenceIdentificationTypeI createConsumerReferenceIdentificationTypeI() {
        return new ConsumerReferenceIdentificationTypeI();
    }

    /**
     * Create an instance of {@link ItemNumberIdentificationTypeI }
     * 
     */
    public ItemNumberIdentificationTypeI createItemNumberIdentificationTypeI() {
        return new ItemNumberIdentificationTypeI();
    }

    /**
     * Create an instance of {@link OriginatorIdentificationDetailsTypeI }
     * 
     */
    public OriginatorIdentificationDetailsTypeI createOriginatorIdentificationDetailsTypeI() {
        return new OriginatorIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link InternalIDDetailsTypeI }
     * 
     */
    public InternalIDDetailsTypeI createInternalIDDetailsTypeI() {
        return new InternalIDDetailsTypeI();
    }

    /**
     * Create an instance of {@link FareCalculationCodeDetailsTypeI }
     * 
     */
    public FareCalculationCodeDetailsTypeI createFareCalculationCodeDetailsTypeI() {
        return new FareCalculationCodeDetailsTypeI();
    }

    /**
     * Create an instance of {@link FareTypeGroupingInformationTypeI }
     * 
     */
    public FareTypeGroupingInformationTypeI createFareTypeGroupingInformationTypeI() {
        return new FareTypeGroupingInformationTypeI();
    }

    /**
     * Create an instance of {@link DocumentDetailsTypeI }
     * 
     */
    public DocumentDetailsTypeI createDocumentDetailsTypeI() {
        return new DocumentDetailsTypeI();
    }

    /**
     * Create an instance of {@link MarriageControlDetailsTypeI }
     * 
     */
    public MarriageControlDetailsTypeI createMarriageControlDetailsTypeI() {
        return new MarriageControlDetailsTypeI();
    }

    /**
     * Create an instance of {@link AdditionalBusinessSourceInformationTypeI }
     * 
     */
    public AdditionalBusinessSourceInformationTypeI createAdditionalBusinessSourceInformationTypeI() {
        return new AdditionalBusinessSourceInformationTypeI();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsTypeI }
     * 
     */
    public FormOfPaymentDetailsTypeI createFormOfPaymentDetailsTypeI() {
        return new FormOfPaymentDetailsTypeI();
    }

    /**
     * Create an instance of {@link FrequentTravellerInformationTypeI }
     * 
     */
    public FrequentTravellerInformationTypeI createFrequentTravellerInformationTypeI() {
        return new FrequentTravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link TravellerInformationTypeI }
     * 
     */
    public TravellerInformationTypeI createTravellerInformationTypeI() {
        return new TravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link LocationTypeI }
     * 
     */
    public LocationTypeI createLocationTypeI() {
        return new LocationTypeI();
    }

    /**
     * Create an instance of {@link ReferenceTypeI }
     * 
     */
    public ReferenceTypeI createReferenceTypeI() {
        return new ReferenceTypeI();
    }

    /**
     * Create an instance of {@link AdditionalProductTypeI }
     * 
     */
    public AdditionalProductTypeI createAdditionalProductTypeI() {
        return new AdditionalProductTypeI();
    }

    /**
     * Create an instance of {@link SpecificDataInformationTypeI }
     * 
     */
    public SpecificDataInformationTypeI createSpecificDataInformationTypeI() {
        return new SpecificDataInformationTypeI();
    }

    /**
     * Create an instance of {@link SourceTypeDetailsTypeI }
     * 
     */
    public SourceTypeDetailsTypeI createSourceTypeDetailsTypeI() {
        return new SourceTypeDetailsTypeI();
    }

    /**
     * Create an instance of {@link DateAndTimeDetailsTypeI }
     * 
     */
    public DateAndTimeDetailsTypeI createDateAndTimeDetailsTypeI() {
        return new DateAndTimeDetailsTypeI();
    }

    /**
     * Create an instance of {@link FareRulesInformationTypeI }
     * 
     */
    public FareRulesInformationTypeI createFareRulesInformationTypeI() {
        return new FareRulesInformationTypeI();
    }

    /**
     * Create an instance of {@link DataTypeInformationTypeI }
     * 
     */
    public DataTypeInformationTypeI createDataTypeInformationTypeI() {
        return new DataTypeInformationTypeI();
    }

    /**
     * Create an instance of {@link TicketNumberTypeI }
     * 
     */
    public TicketNumberTypeI createTicketNumberTypeI() {
        return new TicketNumberTypeI();
    }

    /**
     * Create an instance of {@link ReservationControlInformationDetailsTypeI }
     * 
     */
    public ReservationControlInformationDetailsTypeI createReservationControlInformationDetailsTypeI() {
        return new ReservationControlInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link RateTariffClassInformationTypeI }
     * 
     */
    public RateTariffClassInformationTypeI createRateTariffClassInformationTypeI() {
        return new RateTariffClassInformationTypeI();
    }

    /**
     * Create an instance of {@link TicketNumberDetailsTypeI }
     * 
     */
    public TicketNumberDetailsTypeI createTicketNumberDetailsTypeI() {
        return new TicketNumberDetailsTypeI();
    }

    /**
     * Create an instance of {@link SystemDetailsTypeI83771C }
     * 
     */
    public SystemDetailsTypeI83771C createSystemDetailsTypeI83771C() {
        return new SystemDetailsTypeI83771C();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsTypeI }
     * 
     */
    public ProductIdentificationDetailsTypeI createProductIdentificationDetailsTypeI() {
        return new ProductIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingSubsequentTypeI }
     * 
     */
    public PricingTicketingSubsequentTypeI createPricingTicketingSubsequentTypeI() {
        return new PricingTicketingSubsequentTypeI();
    }

    /**
     * Create an instance of {@link ProductDateTimeTypeI52040C }
     * 
     */
    public ProductDateTimeTypeI52040C createProductDateTimeTypeI52040C() {
        return new ProductDateTimeTypeI52040C();
    }

    /**
     * Create an instance of {@link LocationTypeI83769C }
     * 
     */
    public LocationTypeI83769C createLocationTypeI83769C() {
        return new LocationTypeI83769C();
    }

    /**
     * Create an instance of {@link ConversionRateDetailsTypeI }
     * 
     */
    public ConversionRateDetailsTypeI createConversionRateDetailsTypeI() {
        return new ConversionRateDetailsTypeI();
    }

    /**
     * Create an instance of {@link MessageFunctionBusinessDetailsTypeI }
     * 
     */
    public MessageFunctionBusinessDetailsTypeI createMessageFunctionBusinessDetailsTypeI() {
        return new MessageFunctionBusinessDetailsTypeI();
    }

    /**
     * Create an instance of {@link LocationDetailsTypeI }
     * 
     */
    public LocationDetailsTypeI createLocationDetailsTypeI() {
        return new LocationDetailsTypeI();
    }

    /**
     * Create an instance of {@link RelatedProductInformationTypeI }
     * 
     */
    public RelatedProductInformationTypeI createRelatedProductInformationTypeI() {
        return new RelatedProductInformationTypeI();
    }

    /**
     * Create an instance of {@link ActionDetailsTypeI }
     * 
     */
    public ActionDetailsTypeI createActionDetailsTypeI() {
        return new ActionDetailsTypeI();
    }

    /**
     * Create an instance of {@link ApplicationErrorDetailTypeI }
     * 
     */
    public ApplicationErrorDetailTypeI createApplicationErrorDetailTypeI() {
        return new ApplicationErrorDetailTypeI();
    }

    /**
     * Create an instance of {@link FareComponentDetailsTypeI }
     * 
     */
    public FareComponentDetailsTypeI createFareComponentDetailsTypeI() {
        return new FareComponentDetailsTypeI();
    }

    /**
     * Create an instance of {@link SelectionDetailsTypeI }
     * 
     */
    public SelectionDetailsTypeI createSelectionDetailsTypeI() {
        return new SelectionDetailsTypeI();
    }

    /**
     * Create an instance of {@link ConsumerReferenceInformationTypeI }
     * 
     */
    public ConsumerReferenceInformationTypeI createConsumerReferenceInformationTypeI() {
        return new ConsumerReferenceInformationTypeI();
    }

    /**
     * Create an instance of {@link StatusTypeI }
     * 
     */
    public StatusTypeI createStatusTypeI() {
        return new StatusTypeI();
    }

    /**
     * Create an instance of {@link OriginatorIdentificationDetailsTypeI83809C }
     * 
     */
    public OriginatorIdentificationDetailsTypeI83809C createOriginatorIdentificationDetailsTypeI83809C() {
        return new OriginatorIdentificationDetailsTypeI83809C();
    }

    /**
     * Create an instance of {@link TaxDetailsTypeI }
     * 
     */
    public TaxDetailsTypeI createTaxDetailsTypeI() {
        return new TaxDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.ReissuedFlownDetails }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.ReissuedFlownDetails createTicketProcessEDocCCConcealedReplyDocGroupReissuedFlownDetails() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.ReissuedFlownDetails();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.StaffTravellerGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.StaffTravellerGroup createTicketProcessEDocCCConcealedReplyDocGroupStaffTravellerGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.StaffTravellerGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.OriginalIssuanceGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.OriginalIssuanceGroup createTicketProcessEDocCCConcealedReplyDocGroupOriginalIssuanceGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.OriginalIssuanceGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup.CarrierFeeInfo }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup.CarrierFeeInfo createTicketProcessEDocCCConcealedReplyDocGroupCarrierFeeGroupCarrierFeeInfo() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.CarrierFeeGroup.CarrierFeeInfo();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup.FareCouponGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup.FareCouponGroup createTicketProcessEDocCCConcealedReplyDocGroupFareElementsGroupFareComponentsGroupPricedFareComponentsGroupFareCouponGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.FareElementsGroup.FareComponentsGroup.PricedFareComponentsGroup.FareCouponGroup();
    }

    /**
     * Create an instance of {@link TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup.CouponGroup }
     * 
     */
    public TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup.CouponGroup createTicketProcessEDocCCConcealedReplyDocGroupDocDetailsGroupCouponGroup() {
        return new TicketProcessEDocCCConcealedReply.DocGroup.DocDetailsGroup.CouponGroup();
    }

}
